name: Build SLTI Android App

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: "21"

      - name: Create Android project
        run: |
          mkdir slti-app
          cd slti-app

          npm init -y

          npm install @capacitor/core@8 @capacitor/android@8
          npm install --save-dev @capacitor/cli@8

          mkdir www
          cp ../index.html www/index.html

          npx cap init "SLTI Secondary Schools" "com.slti.secondaryschools" --web-dir www

          npx cap add android
          npx cap sync android

      - name: Build Android APK and AAB
        working-directory: slti-app/android
        run: |
          chmod +x gradlew
          ./gradlew assembleDebug
          ./gradlew bundleDebug

      - name: Upload Android files
        uses: actions/upload-artifact@v4
        with:
          name: SLTI-Android-App
          path: |
            slti-app/android/app/build/outputs/apk/debug/app-debug.apk
            slti-app/android/app/build/outputs/bundle/debug/app-debug.aab
